[build]
publish = "public"
command = "hugo"

  [build.environment]
  HUGO_VERSION = "0.80.0"

[[headers]]
for = "/*.jpg"
[headers.values]
  Cache-Control = "public, max-age=10000000"

[[headers]]
for = "/*.png"
[headers.values]
  Cache-Control = "public, max-age=10000000"

[[headers]]
for = "/*.css"
[headers.values]
  Cache-Control = "public, max-age=10000000"

[[headers]]
for = "/*.js"
[headers.values]
  Cache-Control = "public, max-age=10000000"

[[headers]]
for = "/*.html"
[headers.values]
  Cache-Control = "public, max-age=10000000"